### ISSUE TITLE
ModuleNotFoundError: No module named 'falco_ui.favicons'

### ISSUE THREAD

**Issue by Mte90** [falcopackages/falco-ui#2]
I was following the guide on https://falco.oluwatobi.dev/the_cli/usage.html and I get this error:

```
Environment `default` already exists
Environment `dev` already exists
Environment `docs` already exists
Python 3.12.7
pre-commit installed at .git/hooks/pre-commit
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/www/indovina/manage.py", line 23, in <module>
    main()
  File "/home/www/indovina/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'falco_ui.favicons'
error: Recipe `run` failed on line 48 with exit code 1
error: Recipe `dj` failed on line 89 with exit code 1
error: Recipe `migrate` failed on line 111 with exit code 1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/www/indovina/manage.py", line 23, in <module>
    main()
  File "/home/www/indovina/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mte90/.local/share/hatch/env/pip-compile/indovina/1N0KV4b0/dev/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'falco_ui.favicons'
error: Recipe `run` failed on line 48 with exit code 1
error: Recipe `dj` failed on line 89 with exit code 1
error: Recipe `createsuperuser` failed with exit code 1
```

Looking in this repository the favicons stuff is missing

**Comment by Mte90** [comment]
The mention is at https://github.com/falcopackages/falco/blob/dab225bbd8c2fa24c9b6b8b70144c6d9dd98a3cb/docs/_static/snippets/settings.py#L98

**Comment by Mte90** [comment]
I see also on https://github.com/falcopackages/starter-template/blob/main/%7B%7B%20cookiecutter.project_name%20%7D%7D/%7B%7B%20cookiecutter.project_name%20%7D%7D/settings.py

**Comment by Mte90** [comment]
It was enough to remove on settings.py and urls.py the mention
